spring:
  datasource:
    druid:
      driver: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/njw_flowable?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=true&serverTimezone=UTC
      username: root
      password: 123456
flowable:
  async-executor-activate: false