spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/njw_flowable?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456
flowable:
  async-executor-activate: false #关闭定时任务
server:
  port: 9999